/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'masahiro' at '15/11/01 9:05' with Gradle 2.8
 *
 * @author masahiro, @date 15/11/01 9:05
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
    static void main(String[] args) {
        println "called main"
    }
}
