/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'masahiro' at '15/11/01 9:05' with Gradle 2.8
 *
 * @author masahiro, @date 15/11/01 9:05
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
